# Generated by Django 4.1.5 on 2023-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kota', models.CharField(blank=True, max_length=200, null=True)),
                ('ciri_khas', models.CharField(blank=True, max_length=200, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kota', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
