# Generated by Django 4.1.5 on 2023-01-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crud',
            new_name='Table',
        ),
    ]
